site_name: Documentación del Proyecto
docs_dir: docs_src
nav:
  - Manual de Usuario: 'docs_src/Manual_de_Usuario.md'
  - Guía de Referencia: 'docs_src/Guia_de_Referencia.md'
  - Guía de Instalación: 'docs_src/Guia_de_Instalacion.md'

extra:
  pdf:
    enable: true
    output: 'docs_src'
    include:
      - 'docs_src/Manual_de_Usuario.pdf'
      - 'docs_src/Guia_de_Referencia.pdf'
      - 'docs_src/Guia_de_Instalacion.pdf'

theme:
  name:theme: mkdocs
